chat/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('admin', views.chat_admin_page, name='chat-admin-page'),
    path('member', views.chat_anggota_page, name='chat-member-page'),
    path('send-chat', views.send_chat, name='send-chat'),
    path('fetch-chats', views.fetch_chats, name='fetch-chats'),
]

home/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name='index'),
]

toys_rent/urls.py
from django.contrib import admin
from django.urls import path, include
from home.views import index

urlpatterns = [
    path('', index, name='home'),
    path('admin/', admin.site.urls),
    path('home/', include(('home.urls', 'home'), namespace="home")),
    path('pengiriman/', include('pengiriman.urls')),
    path('items/', include('items.urls')),
    path('profil/', include('profil.urls')),
    path('login/', include('login.urls')),
    path('pesanan/', include('pesanan.urls')),
    path('level/', include('level.urls')),
    path('review/', include('review.urls')),
    path('chat/', include('chat.urls')),
    path('barang/', include('barang.urls')),
]

templates/navbar.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>

  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="description" content="">
  <meta name="author" content="">

  <title>Toys Rent!</title>

  <!-- Font Awesome Icons -->
  <link href="vendor/fontawesome-free/css/all.min.css" rel="stylesheet" type="text/css">

  <!-- Google Fonts -->
  <link href="https://fonts.googleapis.com/css?family=Merriweather+Sans:400,700" rel="stylesheet">
  <link href='https://fonts.googleapis.com/css?family=Merriweather:400,300,300italic,400italic,700,700italic' rel='stylesheet' type='text/css'>

  <!-- Plugin CSS -->
  <link href="vendor/magnific-popup/magnific-popup.css" rel="stylesheet">

  <!-- Theme CSS - Includes Bootstrap -->
  <link href="{% static '/css/home.css' %}" rel="stylesheet">

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css">
	<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.1/css/all.css">
    <link rel="stylesheet" href="https//cdn.datatables.net/1.10.19/css/jquery.dataTables.min.css">
    <link rel="stylesheet" href="https://cdn.datatables.net/1.10.19/css/dataTables.bootstrap4.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/jquery-modal/0.9.1/jquery.modal.min.css" />
	<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"></script>
	<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js"></script>
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script src="https://cdn.datatables.net/1.10.19/js/jquery.dataTables.min.js"></script>
    <script src="https://cdn.datatables.net/1.10.19/js/dataTables.bootstrap4.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-modal/0.9.1/jquery.modal.min.js"></script>

  
</head>

<body id="page-top">

  <!-- Navigation -->
  <nav class="navbar navbar-expand-lg navbar-light py-3" id="mainNav">
    <div class="container">
      <a class="navbar-brand js-scroll-trigger" href="{% url 'home:index' %}">Toys Rent</a>
      <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav ml-auto my-2 my-lg-0">
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Item</a>
            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
              <a class="dropdown-item" href="{% url 'create_item' %}">Create</a>
              <div class="dropdown-divider"></div>
                    <a class="dropdown-item" href="{% url 'daftar_item' %}">Daftar Item</a>
            </div>
          </li>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Barang</a>
            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
              <a class="dropdown-item" href="{% url 'add-barang' %}">Create</a>
              <div class="dropdown-divider"></div>
              <a class="dropdown-item" href="{% url 'list-barang' %}">Daftar Barang</a>
            </div>
          </li>
         <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Pesanan</a>
            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
              <a class="dropdown-item" href="{% url 'create_pesanan' %}">Create</a>
              <div class="dropdown-divider"></div>
              <a class="dropdown-item" href="{% url 'daftar_pesanan' %}">Daftar Pesanan</a>
            </div>
          </li>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Level</a>
            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
              <a class="dropdown-item" href="{% url 'create_level' %}">Create</a>
              <div class="dropdown-divider"></div>
              <a class="dropdown-item" href="{% url 'daftar_level' %}">Daftar Level</a>
            </div>
          </li>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Pengiriman</a>
            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
              <a class="dropdown-item" href="{% url 'create_pengiriman' %}">Create</a>
              <div class="dropdown-divider"></div>
              <a class="dropdown-item" href="{% url 'daftar_pengiriman' page=1 %}">Daftar Pengiriman</a>
            </div>
          </li>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Review Barang</a>
            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
              <a class="dropdown-item" href="{% url 'daftar_review' %}">Daftar Review</a>
            </div>
          </li>
            {% if request.session.type %}
                {% if request.session.type == "admin" %}
                  <li class="nav-item">
                    <a class="nav-link js-scroll-trigger" href="{% url 'chat-admin-page' %}">Chat</a>
                  </li>
                {% elif request.session.type == "anggota" %}
                    <li class="nav-item">
                        <a class="nav-link js-scroll-trigger" href="{% url 'chat-member-page' %}">Chat</a>
                    </li>
                {% endif %}
            {% endif %}
          {% if request.session.type %}
          <li class="nav-item">
              <a class="nav-link js-scroll-trigger" href="{% url 'profil' %}">Profile</a>
            </li>
          {% endif %}
          <li class="nav-item">
              {% if request.session.type %}
                {% if request.session.type == "anggota" %}
                    <a class="nav-link js-scroll-trigger" href="{% url 'logout' %}">Logout</a>
                {% else %}
                    <a class="nav-link js-scroll-trigger" href="{% url 'logout' %}">Logout</a>
                {% endif %}
              {% else %}
                    <a class="nav-link js-scroll-trigger" href="{% url 'login' %}">Login</a>
              {% endif %}
          </li>
        </ul>
      </div>
    </div>
  </nav>
  {% block content %}
  {% endblock %}
</body>